name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: tonyzzp
        password: ${{secrets.DOCKER_USER_PASSWORD}}
        
    - name: docker build
      run: docker build -t ${{vars.DOCKER_IMAGE_NAME}} .
    
    - name: docker push
      run: docker push ${{vars.DOCKER_IMAGE_NAME}}
